# Generated by Django 2.1.2 on 2018-10-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default='999999', max_length=35),
        ),
    ]
